[tool.ruff]
line-length = 88
fix = true
unsafe-fixes = false

[tool.ruff.lint]
select = ["E", "F", "I", "B", "W", "C90"]
ignore = ["E501"]  # Let black handle line length

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "ANN"]
